codecov:
  # Default branch for CodeCov information
  branch: 4.x

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        branches:
          - 4.x
          - 5.x
    patch:
      default:
        target: 90%
        threshold: 1%
        branches:
          - 4.x
          - 5.x
