convert_opt:
  path: /convert
  methods: OPTIONS
  controller: App\Islandora\Homarus\Controller\HomarusController::convertOptions
convert_get:
  path: /convert
  methods: GET
  controller: App\Islandora\Homarus\Controller\HomarusController::convert
