# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.executable: ffmpeg
    app.formats.valid:
        - mimetype: video/mp4
          format: mp4
        - mimetype: video/x-msvideo
          format: avi
        - mimetype: video/ogg
          format: ogg
        - mimetype: audio/x-wav
          format: wav
        - mimetype: audio/mpeg
          format: mp3
        - mimetype: audio/aac
          format: m4a
        - mimetype: image/jpeg
          format: image2pipe
        - mimetype: image/png
          format: image2pipe
    app.formats.defaults:
        mimetype: video/mp4
        format: mp4
    app.tempDirectory: /../public/static/

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Islandora\Homarus\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Islandora\Homarus\Controller\HomarusController:
        public: false
        bind:
            $formats: '%app.formats.valid%'
            $defaults: '%app.formats.defaults%'
            $executable: '%app.executable%'
            $tempDirectory: '%app.tempDirectory%'
        tags: ['controller.service_arguments']
