# config/routes.yaml

app_fits_exec:
  path: /fits/process
  controller: App\Controller\FitsController::generate_fits

app_fits_exec2:
  path: /
  controller: App\Controller\FitsController::generate_fits
