---

debug: false 

# Leave these blank unless you know what you're doing.  If you're moving
# data from one server to another and the domain changes, set these
# to your new domain.
fedora_domain: 
drupal_domain: 

db.options:
  driver: pdo_mysql
  host: 127.0.0.1
  port: 3306
  dbname: gemini
  user: changeme
  password: changeme

log:
  # Valid log levels are:
  # DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY, NONE
  # log level none won't open logfile
  level: NONE
  file: ../gemini.log

syn:
  # toggles JWT security for service
  enable: false
  # Path to the syn config file for authentication.
  # example can be found here:
  # https://github.com/Islandora/Syn/blob/main/conf/syn-settings.example.xml
  config: ../syn-settings.xml
