#!/bin/sh
export SYMFONY_DEPRECATIONS_HELPER=disabled
FAIL=0
for D in */; do
  echo "::group::Testing $D"
  cd $D
  composer test
  if [ $? -ne 0 ]; then 
    FAIL=1
  fi 
  cd ..
  echo "::endgroup"
done
exit $FAIL
