---

fedora_resource:
  base_url: http://localhost:8080/fcrepo/rest

gemini_base_url: http://localhost:8000/gemini

drupal_base_url: http://localhost:8000

debug: false

log:
  # Valid log levels are:
  # DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY, NONE
  # log level none won't open logfile
  level: NONE
  file: ../recast.log

syn:
  # toggles JWT security for service
  enable: false
  # Path to the syn config file for authentication.
  # example can be found here:
  # https://github.com/Islandora-CLAW/Syn/blob/master/conf/syn-settings.example.xml
  config: ../syn-settings.xml