---

fedora_resource:
  base_url: http://localhost:8080/fcrepo/rest

gemini_base_url: http://localhost:8000/gemini

drupal_base_url: http://localhost:8000

debug: false

log:
  # Valid log levels are:
  # DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY, NONE
  # log level none won't open logfile
  level: NONE
  file: ../recast.log

syn:
  # toggles JWT security for service
  enable: false
  # Path to the syn config file for authentication.
  # example can be found here:
  # https://github.com/Islandora-CLAW/Syn/blob/master/conf/syn-settings.example.xml
  config: ../syn-settings.xml

# Add namespace prefixes used by Fedora for recast service
# Must be inside an array to maintain the internal associative array.
namespaces:
-
  acl: "http://www.w3.org/ns/auth/acl#"
  fedora: "http://fedora.info/definitions/v4/repository#"
  ldp: "http://www.w3.org/ns/ldp#"
  memento: "http://mementoweb.org/ns#"
  pcdm: "http://pcdm.org/models#"
  pcdmuse: "http://pcdm.org/use#"
  webac: "http://fedora.info/definitions/v4/webac#"
  vcard: "http://www.w3.org/2006/vcard/ns#"
