name: CI - PHP 8.4 / Symfony 8.1

on:
  push:
    branches: [4.x, 5.x]
  pull_request:
    branches: [4.x, 5.x]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP 8.4
    defaults:
      run:
        working-directory: Milliner
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45 # v2
        with:
          php-version: "8.4"
          tools: composer:v2
          coverage: xdebug

      - name: Validate Composer configuration
        run: composer validate --strict --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Audit dependencies
        run: composer audit --locked --abandoned=fail

      - name: Check coding standards
        run: composer check

      - name: Test with coverage
        run: composer coverage
        env:
          XDEBUG_MODE: coverage

      - name: Upload coverage
        uses: codecov/codecov-action@04b047e8bb82a0c002c8312c1c880fbc6a999d45 # v5
        with:
          files: Milliner/clover.xml
          fail_ci_if_error: true
